### ISSUE TITLE
Create NPM package for core types

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-core#12]
**Description**
The Mento SDK will need access to the interfaces defined in the Mento core project. To keep these in sync easily we need to have these types generated automatically when they are updated in the core repo. Create an NPM mento core npm package that contains typescript types, factories & deployed addresses for each contract.

**Acceptance Criteria**
- [ ] Addresses for each accessible type are available in the package
- [x] Typescript types for each contract is available in the package
- [x] Mento npm organisation

**Comment by philbow61** [comment]
#78
