### ISSUE TITLE
Get MentoV2 included in Minima

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#123]
**Description**
Minima is an on-chain router that allows consumers to find and execute swaps with the best prices on CELO. The router consists of a public API(documentation [here](https://docs.router.nodefinance.org/)) and [smart contracts](https://github.com/Node-Fi/Minima-Contracts) that return quotes and execute swaps. The Minima contracts seem to be a forked and modified version of Swappa, so the integration effort will be very similar.

In order to integrate MentoV2 we will need to do the following:
- Add new MentoV2 contract that inherits from SwappaPair

**Acceptance Criteria**

- [ ] PR opened with new contract added

**Comment by bayological** [comment]
- Closed source
- Low volume <2k
- No response in Discord
