### ISSUE TITLE
Create Mento SDK repo

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#13]
**Description**
Create a new repo, mento-sdk, that provides access to functions and types to simplify interaction with Mento core contracts for the interface. The repo should have a CI pipeline set up that will build, test and push a versioned NPM package to the public NPM repository.

**Acceptance Criteria**
- [x] Repo has policies set up
- [x] CI pipeline is set up with tasks to build, test & publish NPM package

**Comment by ninocomputer** [comment]
https://github.com/mento-protocol/mento-sdk/pull/1
