### ISSUE TITLE
Create a testnet USDC ERC20 token

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#138]
**Description**

In order to test Mento in a configuration similar to Production (Mainnet) we need a USDC token on Baklava and Alfajores. The purpose of this task is to create an ERC20 token that acts as USDC for our protocol.

**Acceptance criteria**

- [x] The token should live in the `mento-deployment` repository as it is just a utility contract for testnet deployments and not part of the protocol core. 
- [x] The token should implement `mint` but be restricted to the owner
- [ ] The owner should be the mento deployer account 
- [ ] The token should be deployed to Alfajores and Baklava and the address should be recorded in the [`dependency.json`](https://github.com/mento-protocol/mento-deployment/blob/main/script/upgrades/dependencies.json) file

> Reach out to @bowd for the deployer PK

**Comment by tobikuhlmann** [comment]
https://github.com/mento-protocol/cross-chain-pair/blob/main/src/MintableERC20.sol here is a token I created earlier which can be used as a skeleton. It is mintable by everyone though
