### ISSUE TITLE
Investigate and decide on release & versioning process for all SDK related packages

### ISSUE THREAD

**Issue by ole-nov** [mento-protocol/mento-core#14]
**Description**

The mento SDK will depend on the mento-core NPM package which will be generated by new builds from the main branch of mento-core. We need to be clear on how we're going to tag the packages & releases as they are generated.

**Acceptance Criteria**

- [ ] Document the release process in notion: tagging & versioning, publishing to NPM and github releases
- [ ] Configure github releases for `mento-core` and `mento-sdk`
- [ ] Ensure both `mento-core` and `mento-sdk` releases are triggered manually in CI

**Comment by ninocomputer** [comment]
https://www.notion.so/Release-process-and-versioning-78bd7021a39a4fdf8e7495174a19d676
