### ISSUE TITLE
Set defaults for breakers in the deploy phase

### ISSUE THREAD

**Issue by ghost** [mento-protocol/mento-core#174]
**Description**
- Median and value delta breakers need default treshold and cooldown time configuration. [MedianDeltaBreaker here](https://github.com/mento-protocol/mento-core/blob/develop/contracts/MedianDeltaBreaker.sol#L35) and [ValueDeltaBreaker here](https://github.com/mento-protocol/mento-core/blob/develop/contracts/ValueDeltaBreaker.sol#L41)
- Right now they are set to 0
- Configuration
  - On median delta breaker [configuration](https://github.com/mento-protocol/mento-deployment/blob/main/script/upgrades/MU01/governance/Config.sol#L308) all median delta breakers for cUSDCELO, cEURCELO, cBRLCELO are set to: 
```
medianDeltaBreakerThreshold: FixidityLib.newFixedFraction(3, 100), // 0.03
medianDeltaBreakerCooldown: 30 minutes
```
  - On value delta breaker [configuration](https://github.com/mento-protocol/mento-deployment/blob/main/script/upgrades/MU01/governance/Config.sol#L308) all value delta breakers for cUSDUSDC are set to: 
```
valueDeltaBreakerThreshold: FixidityLib.newFixedFraction(5, 1000), // 0.005
valueDeltaBreakerCooldown: 1 seconds
```

**Acceptance Criteria**
- Since breakers are the same for all pairs respectively for median and value delta breaker, set the defaults already to these values

**Comment by tobikuhlmann** [comment]
closing as agreed on 0 default values
