### ISSUE TITLE
Verify all Mento V2 contracts on celoscan.io

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-core#187]
**Description**

Atm all Mento contracts are verified on Blockscout (explorer.celo.org). There is also Etherscan explorer on Celo (celoscan.io). Potential partners from other ecosystems are looking at this explorer (e.g. it was one of the questions that Tally asked me, and then Angle as well). But our contractds are not verified on Celoscan.io

**Acceptance Criteria**

All Mento V 2.0  and V 2.1 contracts from the list in the docs should be verified on celoscan.io https://docs.mento.org/mento/developers/deployments/addresses

**Comment by ninocomputer** [comment]
Mento v2

BiPoolManagerProxy - https://celoscan.io/address/0x22d9db95e6ae61c104a7b6f6c78d7993b94ec901#code
BiPoolManager - https://celoscan.io/address/0x9f6dac2d571d8f727d762c82af240a170c42193a#code
BrokerProxy - https://celoscan.io/address/0x777a8255ca72412f0d706dc03c9d1987306b4cad#code
Broker - https://celoscan.io/address/0x5cb8fb4cf7247de5fd514243d72b5e90c1b7bab7#code

**Comment by ninocomputer** [comment]
Thanks 🫀 Exchange contracts are verified they're linked in mentov1 section @philbow61

**Comment by bowd** [comment]
👍 LGTM we can close!
