### ISSUE TITLE
Verify linting step is running as part of the CI workflow

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-core#197]
**Description**

We need to confirm the functionality of the linting step in our CI workflow. Specifically, we need to ensure that this step is actually identifying and reporting any linting errors in the code. The expected result is a linting step that functions correctly, successfully detecting any code inconsistencies and causing the job to fail when any linting errors are present.

**Comment by ninocomputer** [comment]
Ci lint and test fails. I think it could potentially be the changes introduced in the foundry's latest release. haven't investigated further but the same tests failed on main/develop after manually triggering the ci. 

https://github.com/mento-protocol/mento-core/actions/runs/5156679996
