### ISSUE TITLE
Build a value based constant sum pricing module

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/mento-core#206]
**Description**

[TODO] - To be updated once final implementation is clear.

The current constant sum pricing module is doing a token amount based constant sum.
Meaning: 
`Amount(bucket0) + Amount(bucket1) = K ` with K being the constant sum. 
This means that basically `amountIn = amountOut `.
 
This ticket is about changing the logic to calculate the constant sum based on the value in both buckets. 
In order to do that we will need to pass the bucket sizes into the calculation.

**Base Formular:**
`X*p + Y = K ` with: 
`X :=amount of bucket0`
`p :=price of one X in Y` 
`Y :=amount of bucket1`
`K := combined value`

For a trade of `x := amountIn` and `y := amountOut` this means 
`(X+x)*p + Y-y = K`
`=> (X+x)*p + Y - K = y`
`=> (X+x)*p + Y - (X*p +Y) = y`
`=> X*p + x*p - X*p  = y`
`=> x*p = y`

Since the BipoolManager uses the exchange rate to calculate the bucket sizes we can use the ratio of the bucket sizes for our `price := p`.
Additionally, we also want to apply the spread to each swap.

**Acceptance Criteria**

- [x] Value-based Constant Sum Pricing Module is created & tested

**Comment by bayological** [comment]
I'm going to remove this from the sprint until we have more clarity on what the final implementation should look like. Once we do we can re-add and update the code on this branch.
