### ISSUE TITLE
SPIKE: Investigate and determine the best solution for the constant sum bug

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-core#214]
**Description**
The goal of this spike is to determine the most suitable approach to update the BiPoolManager, ConstantSumPricingModule, and, potentially, the IPricingModule Interface. Currently, the ConstantSumPricingModule calculates a constant sum based on the token amounts in the buckets, which will result in sub-optimal outcomes when pairs do not trade at 1-1.

The main focus will be on:
- investigating solutions that calculate the constant sum based on the token value, not the token amounts
- Determine the best way to update the interface of the pricing modules if necessary.

More information on bug [here](https://www.notion.so/ConstantSum-Problem-e7a9cc4cc3bd4ff5aa2577f85373daa4)

**Acceptance Criteria**
- [x]  [Notion doc](https://www.notion.so/ConstantSum-Problem-e7a9cc4cc3bd4ff5aa2577f85373daa4) is updated with solution
- [x] Solution is reviewed by economics team
- [x] [Issue](https://github.com/mento-protocol/mento-core/issues/206) is updated to reflect what needs to be done to implement the fix

**Comment by philbow61** [comment]
https://www.notion.so/ConstantSum-Problem-e7a9cc4cc3bd4ff5aa2577f85373daa4

**Comment by bayological** [comment]
Nice work 🎖️
