### ISSUE TITLE
[M-1] setTokenPrecisionMultipliers allows arbitrary decimal multipliers

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#238]
When the `BiPoolManager` creates an exchange, after performing several validations on the inputs, the token precision multipliers are set in order to deal with assets with different token decimals while calculating swap amounts. 

For example, `USDC` has `6` decimal places, having a token precision multiplier of `1000000000000` (`10 ** (18 - 6)`), as we can see in the function’s logic:

```solidity
tokenPrecisionMultipliers[exchange.asset0] = 10**(18 - uint256(IERC20Metadata(exchange.asset0).decimals()));
tokenPrecisionMultipliers[exchange.asset1] = 10**(18 - uint256(IERC20Metadata(exchange.asset1).decimals()));
```

However, the function `setTokenPrecisionMultipliers` allows to arbitrarily change the token precision multipliers, in this case, say for `USDC`, from `1000000` to an arbitrarily large or small value. Which would then affect the calculations in the swap in/out and in the get amounts in/out functions.

Additionally, the function doesn’t check whether the tokens are valid and registered with the `Reserve` contract. 

**Remediations to Consider**

- Perform the same proper input validations implemented in the `createExchange` function or
- Remove the `setTokenPrecisionMultipliers` from the contract. 🙅‍♂️

**Acceptance Criteria**

- [x] `setTokenPrecisionMultipliers` verifies tokens are valid reserve stable or collateral assets
- [x] `setTokenPrecisionMultipliers` verifies precision multiplier values are in a valid range

**Comment by bayological** [comment]
We shouldn't remove the function. So we should perform the same validations in the function to check the decimals are within a valid range (as done in create function) and verify that the assets are either collateral assets or stable assets in the reserve. These validations will increase execution cost but this is a minor point as this method will be called by governance and will not be called often.
