### ISSUE TITLE
Update IBiPoolManager pool config variables

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-core#24]
**Description**
Update the naming of the pool config variables and their usage.

**Acceptance Criteria**

- [x] [bucket0MaxFraction](https://github.com/mento-protocol/mento-core/blob/feature/mcmint/contracts/interfaces/IBiPoolManager.sol#L41) is removed
- [x] [bucketUpdateFrequency](https://github.com/mento-protocol/mento-core/blob/feature/mcmint/contracts/interfaces/IBiPoolManager.sol#L38) renamed to `referenceRateResetFrequency`
- [x] [bucket0TargetSize](https://github.com/mento-protocol/mento-core/blob/feature/mcmint/contracts/interfaces/IBiPoolManager.sol#L40) renamed to `stablePoolResetSize`

**Comment by philbow61** [comment]
[Pull Request](https://github.com/mento-protocol/mento-core/pull/26)
