### ISSUE TITLE
[Q-2] The function removeRateFeed() doesn’t delete the rate feed dependencies

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-core#247]
**Description**
In the `BreakerBox` contract, a `rateFeedId` could have a set of rate feed dependencies mapped to it via the `setRateFeedDependencies` function. 

However, when a rate feed is removed, its dependencies are not deleted. 

**Remediations to Consider**

Consider adding the following line to the `removeRateFeed` function

`delete rateFeedDependencies[rateFeedID];`

**Comment by bayological** [comment]
**Story Points: 1**
  [See the discussion](https://action.parabol.co/meet/phLg0LXAVa/estimate/6) in Sprint Poker #​​17

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ninocomputer** [comment]
https://github.com/mento-protocol/mento-core/pull/260
