### ISSUE TITLE
Spike: Emission contract

### ISSUE THREAD

**Issue by baroooo** [mento-protocol/mento-core#265]
**Description**
65% of the Mento Token supply will be emitted through an emission contract. Emission contract should unlock tokens based on a predefined exponential decaying formula and a permissionless function should trigger transfers

Research and document:
- [x] What should be the formula? Discuss with @rcroessmann 
- [x] How Sablier works, and how we can integrate? https://github.com/sablier-labs/v2-core
- [x] Curve gauges and check how that can work with emission contract?

**Acceptance Criteria**
- [x] A document answering questions above
- [x] Update project page accordingly: https://www.notion.so/Mento-Token-and-Governance-ae6acced7b4d465db90f92f1408ee23c?showMoveTo=true&saveParent=true
- [x] Create github issues for the implementation of the contract

**Comment by baroooo** [comment]
Spike docs: https://www.notion.so/Spike-Emission-contract-a3389802add2438ca482c6d18a607a2f
Project page updated: https://www.notion.so/Mento-Token-and-Governance-ae6acced7b4d465db90f92f1408ee23c
New issues created: [#305](https://github.com/mento-protocol/mento-general/issues/305) and [#306](https://github.com/mento-protocol/mento-general/issues/306)

**Comment by ninocomputer** [comment]
lgtm! Did you explore alternatives to Sablier, considering that their solution seems to be too complex for what we want?
