### ISSUE TITLE
Create a testnet deployment script for all contracts

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#28]
**Description**

Create a Foundry script that deploys the latest version of contracts to Alfajores.
It should also include submitting a CGP to the testnet to update the relevant contracts (Reserve, StableTokens, etc.).

[Testnet Deployment Runbook](https://www.notion.so/CGP-Testing-Testnet-Deployment-eb5b747dc1c84fa8bca491ed74b7f942-d7f822df9903422abc3c3c59795d1fb4)

Deployment:

- Outside of Governance Proposal
    - Deploy implementations: ✅
        - Broker ✅
        - BiPoolManager ✅
    - Deploy proxies for: ✅
        - Broker ✅
        - BiPoolManager ✅
    - Set proxy implementations and transfer ownership to Governance for: ✅
        - Broker ✅
        - BiPoolManager ✅
    - Deploy stateless contracts: ✅
        - ConstantProductPricingModule ✅
        - ConstantSumPricingModule ✅
    - Deploy updated implementations: ✅
        - StableToken(USD,EUR,REAL) ✅
        - Reserve ✅
- Inside of Governance Proposal:
    - Update proxy implementation: ✅
        - StableToken(USD,EUR,REAL) ✅
        - Reserve ✅
    - Set Broker as Reserve exchange spender✅
    - Add pools to the BiPoolManager:✅
        - cUSD/CELO✅
        - cEUR/CELO✅
        - cREAL/CELO✅
        - cUSD/USDCet✅
    - Set Oracle Report Targets for New Rates

**Acceptance Critera**

- [ ] Scripts are done and tested
- [ ] There's a Baklava deployment

**Comment by bowd** [comment]
Ask for permissions to GCP KeyVault for Alfajores

**Comment by bayological** [comment]
Pull Request: https://github.com/mento-protocol/mento-core/pull/59
