### ISSUE TITLE
Add comments to locking contracts

### ISSUE THREAD

**Issue by baroooo** [mento-protocol/mento-core#288]
## Description
The locking contracts we forked from rarible lack comments and hard to understand. We need to add comments explaining what the functions are doing

### Acceptance Criteria:
- [ ] Contracts are explained using natspec style comments

**Comment by bayological** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/stiXHNi8oM/estimate/3) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
