### ISSUE TITLE
Update airgrab contract and UI to reflect latest KYC criteria

### ISSUE THREAD

**Issue by baroooo** [mento-protocol/mento-core#291]
## Description
The current KYC implementation, both on-chain and off-chain, is not yet complete. Though the Fractal integration is working the following need to be updated so we can test the integration properly end to end.

**Airgrab Contract**
-  [Expected credential](https://github.com/mento-protocol/mento-core/blob/18d46e226ca2a884969d25564cb8641b371d15fc/contracts/governance/Airgrab.sol#L103) is not complete. Currently, we are only excluding Canada and US residents. The level of KYC required should be plus (as basic doesn't allow residency restrictions) and we need to ensure that this level excludes residents of countries in the following screenshot taken from the [token FAQ](https://docs.google.com/document/d/1iTQWNoFAX-cXClBlyBpiBb0atl1e_ujnA6xJGJl45Jc/edit):

<img width="669" alt="Screenshot 2024-03-13 at 17 44 25" src="https://github.com/mento-protocol/mento-core/assets/4562733/16410926-9143-42de-a688-7ed0e863079b">

**Airgrab Interface**
- The KYC message is slightly off; this causes the proof request to fail. Instead of using a static message, we should use the message generator as done [here](https://github.com/mento-protocol/governance-tests/blob/73d71f2f42574c38b46761c30e9e00a3133f64fb/test/getMessage.ts#L24)

**KYC Level**
The Airgrab contract requires the [plus](https://docs.developer.fractal.id/kyc-levels) KYC level. However, the interface is set up only to complete basic. We need to update the interface and contract to reflect this.

## Acceptance Criteria

- [ ] Airgrab contract is updated to require the correct credentials
- [ ] KYC message generator is added to the UI and replaces the [static message](https://github.com/mento-protocol/airgrab-interface/blob/8fa5d772a85f4a5d2502b48338c9400c0e2c1d74/src/lib/constants.ts#L18)
- [ ] Interface requests plus KYC level instead of basic

**Comment by bayological** [comment]
This is still requires confirmation from legal on what the actual countries to be excluded are.

**Comment by nvtaveras** [comment]
Update on this after a conversation with @olenovyk . The final list is the following:

<img width="1368" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMExTQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7b6dbba26b5a603d286f0a436898cf71f9eaa8b3/Screenshot%202024-03-12%20at%2014.35.45.png" alt="Screenshot 2024-03-12 at 14.35.45.png" />

we however would *not* want to have the other restrictions that come with Fractal by using the plus KYC Level (European Commission’s list of high-risk third countries and the FATF monitored and call-for-action lists). 

@olenovyk will reach out to Fractal to see if it's possible to use the plus KYC level with our own list of restrictions. If the answer is no, we will have to re-visit both the KYC level and the restrictions.

**Comment by nvtaveras** [comment]
Final update after talking to Fractal, it seems like we misunderstood and the plus KYC level does not include restrictions by default. We can just manually block the countries in the previous comment and we are good to go.
