### ISSUE TITLE
Migration plan for deprecating the Mento Exchange contracts in favour of the Broker

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#30]
### Description

Mento currently works by interacting with an Exchange instance for each cStable.
In McMint this changes to a single Broker instance that delegates internally to different ExchangeProviers.

When deploying McMint we need a plan for phasing out the Exchange instances, potentially by making the bucket sizes smaller. And reverting their access to mint stables.

### Acceptance criteria

- Include a migration plan in the design doc

**Comment by bayological** [comment]
@bowd @sissnad I have an initial version [here](https://docs.google.com/document/d/1jdAv3wstYVCHJS3O5kzx9rzo-odIHh8_Fds8r1la76M/edit#) but think we need to confirm pool params & trading limits for existing and new pools.
