### ISSUE TITLE
Macro Audit Findings

### ISSUE THREAD

**Issue by baroooo** [mento-protocol/mento-core#301]
## Description
Fix the findings from the Macro audit: https://www.notion.so/0xmacro/Mento-2-Preliminary-Audit-Report-external-private-9a2a743bddb0450b8e7914a4ccc96704
Fill the fixes doc: https://www.notion.so/0xmacro/Mento-2-Fixes-381c9db5a6ae4027b1323e79aecf2d3a 

### Findings:
- [Q-2]
- [Q-3]
- [Q-4]
- [Q-5]
- [Q-7]
- Correct typo - https://github.com/mento-protocol/mento-core/blob/feat/factory-contract-leftovers/contracts/governance/Emission.sol#L92

### Acceptance Criteria:
- [x] Findigs above are fixed
- [x] Fixes doc addresses commits for fixed issues and responses for unfixed ones

**Comment by bayological** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/stiXHNi8oM/estimate/2) in Sprint Poker #​​26

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by baroooo** [comment]
This waits for https://github.com/mento-protocol/mento-core/pull/318 to be merged
