### ISSUE TITLE
Deploy and run Factory on Alfajores

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#303]
**Description**

Execute the Governance Factory deployment script on Alfajores

**Acceptance criteria**

- [ ] Factory is deployed
- [ ] Governance is created
- [ ] Post deployment checks passed

**Comment by bayological** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/sEXKhr2Snm/estimate/3) in Sprint Poker #​​27

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
