### ISSUE TITLE
Investigate celocli network:contracts

### ISSUE THREAD

**Issue by nvtaveras** [mento-protocol/mento-core#309]
The celocli network:contracts command is broken after running MU04 on Baklava, likely due to us setting the address in the registry for `Exchange`, `ExchangeEUR`, `ExchangeBRL` and `GrandaMento` to `0x...000`. We should fix the CLI or find out if it's ok to go through with this proposal without updating the old registry addresses.

**Comment by philbow61** [comment]
https://github.com/celo-org/celo-monorepo/pull/10792
