### ISSUE TITLE
Make the Broker capable of minting StableTokens

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#32]
### Description

The Broker Contract needs permission to mint/burn mento stables when executing swaps. In order to not break the patterns used in StableToken we will do this by: 
- Registering the Broker Contract in the Registry with identifier `keccak256(abi.encodePacked("Broker"))` (see GRANDA_MENTO_REGISTRY_ID in StableToken.sol)
- Add another condition in the mint/burn functions of stable token checking if the caller is the broker address from registry

### Acceptence criteria

- StableToken si modified to look-up the Broker in the registry and allow minting/burning.
- Integration tests no longer use the `exchangeRegistryId` variable in StableToken  (set to "Broker") to allow minting.

**Comment by philbow61** [comment]
Pull Request #57
