### ISSUE TITLE
Rework Slither Setup: Implementation according to spec doc

### ISSUE THREAD

**Issue by chapati23** [mento-protocol/mento-core#324]
### Description

Fix & upgrade slither setup and processes according to [spec doc](https://www.notion.so/Make-Slither-Great-Again-a633364c388349188f7372f680e93da3?pvs=4)

### Acceptance Criteria

- [ ] `slither.db.json` file is gone and has been replaced with inline annotations )and explanatory comments where applicable)
- [ ] CI setup has been updated
- [ ] Local `slither` setup & process has been updated and was communicated to the team

**Comment by bayological** [comment]
We should discuss this in more detail, the first point in this AC is not a small task

**Comment by chapati23** [comment]
@bowd did this as part of his CI updates
