### ISSUE TITLE
Come up with the calculation of the locking/relocking parameters

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/mento-core#341]
**Description:**
In order to implement the vesting plan setup as described [here](https://www.notion.so/mentolabs/Team-and-Investor-Vesting-1848377e659647baa13aac7675761f88) we need to come up with the math and logic that calculates the parameters for the lock/relock depending on the time point the redeem function is called. 

Since this calculation probably also depends on the parameters of the underlying vesting plan, part of this ticket should also be coming up with a standardized way of creating/parameterizing vesting plans e.g which weekday should be the start, how large should the period be(hopefully weekly)... ?

## Acceptance Criteria

- [ ] **1:come up with a calculation logic for locking/relocking parameters**
  - Given a vesting plan setup
  - When the redeem function is called at a specific time point
  - Then the locking/relocking parameters should be calculated how?
  
- [ ] **2: clarify what should be used as parameters for the hedgey [createPlan](https://github.com/hedgey-finance/Locked_VestingTokenPlans/blob/c30737bc5603aba6e6c600a6b2c5462db198f8e3/contracts/VestingPlans/TokenVestingPlans.sol#L47)() function**
- [ ] **3: update the notion based on the outcome of this ticket**

**Comment by bayological** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/tJicNwgOk0/estimate/2) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
