### ISSUE TITLE
Vesting contracts testing plan

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/mento-core#343]
## Description:

We need to come up with a testing  plan for the Vesting contracts that verify the integration between 
MentoToken-TokenVestingPlans.sol(Hedgey)-VestingLock.sol-Locking.sol-VestingPlanRecipient works as expected.
This Ticket is about coming up with different scenarios that should be tested on a fork so we can utilize the existing hedgey deployments.

## Acceptance Criteria

- [x] 1: Vesting contracts testing plan is designed and documented in notion

**Comment by bayological** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/tJicNwgOk0/estimate/1) in Sprint Poker #​​30

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by baroooo** [comment]
The plan is ready for review: https://www.notion.so/mentolabs/Vesting-Contracts-Testing-Plan-7c2afcbc7b374775b86174fc975fc727

**Comment by philbow61** [comment]
LGTM 👍

**Comment by denviljclarke** [comment]
LGTM 🫡
