### ISSUE TITLE
Write vesting contract integration tests

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/mento-core#344]
# Description: 
Implement the integration test described in [notion](https://www.notion.so/mentolabs/Team-and-Investor-Vesting-1848377e659647baa13aac7675761f88)

## Acceptance Criteria

- [ ] **1: Implement integration test for vesting contract**

**Comment by bayological** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/tYhknXDPJS/estimate/18) in Sprint Poker - 25th Jan

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
