### ISSUE TITLE
Circuit breaker integration with McMint

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-core#35]
**Description**
The existing circuit breaker implementation is designed to work with the existing exchanges. With the McMint update, these exchanges will be deprecated, so the circuit breaker needs to be modified to work with the McMint broker instead.

Existing branch: https://github.com/celo-org/celo-monorepo/tree/bayological/onchain-circuit-breaker

**Acceptance Criteria**

- [x] Existing circuit breaker code is migrated to mento-core repo
- [x] Circuit breaker stops trading via mento when a shift gt a calculated amount in oracle reports is detected
- [x] Breaker automatically resets itself after it has been tripped based on it's configured params
- [x] Tests are added to verify functionality works as expected

**Comment by ninocomputer** [comment]
https://github.com/mento-protocol/mento-core/pull/56
