### ISSUE TITLE
[Bug] Email notification flow is not working

### ISSUE THREAD

**Issue by olenovyk** [mento-protocol/mento-core#356]
After completing email form, I see "Submitting..." button and nothing happens.<img width="1008" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3I3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--737bfbf3437e18e4083f60cd925526e8f4b05a3d/Screenshot%202024-01-25%20at%2012.33.44.png" alt="Screenshot 2024-01-25 at 12.33.44.png" />

*Acceptance criteria*

- [x] I should see confirmation screen once email is submitted
- [ ] Email should be saved somewhere

**Comment by denviljclarke** [comment]
@olenovyk There was an environment variable issue, please check this again. Please not you can't use a dispostable email as it's seen as an invalid email by mailchimp

[Link to prelaunch app](https://prelaunch-airgrab-interface.vercel.app/allocation)

**Comment by bayological** [comment]
@olenovyk @denviljclarke I have checked this and verified it is working as expected. I've raised a separate [issue](https://github.com/mento-protocol/airgrab-interface/issues/55) related to this that would require a code change but is a small fix.

**Comment by olenovyk** [comment]
worked for me as well now
