### ISSUE TITLE
Modify locking voting power formula

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#373]
**Description** 

Currently the voting power formula looks like this (slightly simplified):

```math
P(t,s,c) = t * (0.2 + 0.8 * c / c_{max} + 0.6 * s / s_{max})
```

This has the following properties:
1. Locking for the minimum times still gives you 20% of your token as voting power.
2. Locking for the full cliff gives you 100% of the voting power.
3. Adding a slope boosts the voting power beyond 100%.

After discussion, we have decided that we don't see the utility of some of these properties. So, we want to bring the system closer to the classical veCurve formula, by changing it to:

```math
P(t,s,c) = t * min(s/s_{max} + c/c_{max}, 1)
```

> In reality, we need to scale both `cliff` and `slope` between a minimum value and a maximum. $$s/s_{max}$$ should be replaced with $$(s - s_{min}) / (s_{max} - s_{min})$$, it is equivalent to $$s/s_{max}$$ when $$s_{min} = 0$$ I used the simplified version not to complicate the intent behind the formula.

This gives us that you can achieve 100% by maxing out either `slope` or `cliff` individually or a linear combination of the two. 
The formula will ensure that the final multiplier is capped at 100% and has the downside of allowing for disadvantageous scenarios. We could consider reverting if the calculated multiplier is > 1 and thus forcing the UI to choose only advantageous scenarios. But this might bring issues because of rounding ( i.e. `P(t,s',c') = 0.95 and P(t, s'+1,c') = 1.05 and P(t, s', c'+1) = 1.02` ). 

We also need to research a bit more into whether this change will affect any assumptions made in the implementation.

**Acceptance criteria**

- [ ] Formula is implemented and thoroughly tested against future scenarios.
- [ ] Enough time is spent understanding what effect it could have on the code.

**Comment by bowd** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/ux9fEFMjGU/estimate/1) in Sprint Poker #​​36

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by baroooo** [comment]
I swlightly changed the issue description because I think the old one was confusing the slope with cliff. Slope should give only 0.6 when maxed:
```
2. Locking for the full slope gives you 100% of the voting power.
3. Adding a cliff boosts the voting power beyond 100%.```

**Comment by bowd** [comment]
True dat, I reversed them in my head. I think I probably imagined that they would make sense like that because using only slope would mean you go from 20-100% and would feel closer to Curve's implementation. Makes sense that they value cliff more tho, lack of progressive unlock and all.

**Comment by bowd** [comment]
Replaced the images with math blocks, they render nice on github but not here :))
Also added that comment about scaling between min and max for extra clarity.

**Comment by chapati23** [comment]
i've reflected the formula update in our original notion project doc: https://www.notion.so/mentolabs/Mento-Token-and-Governance-ae6acced7b4d465db90f92f1408ee23c?pvs=4#82285ce8f4654e3c9bdfe26d44c5651d
