### ISSUE TITLE
[Audit Finding] Locking with a cliff is more effective than using a slope

### ISSUE THREAD

**Issue by chapati23** [mento-protocol/mento-core#380]
### Description 
Address audit finding: https://www.notion.so/0xmacro/Mento-3-Preliminary-Audit-Report-external-private-06ee6ce11d7d4df0a950ca97c75a2766?pvs=4#71a201143b454cfeae9a94782828cf30

- [x] decided on not to change those explain why 
- [x] Address finding

**Comment by baroooo** [comment]
Added our decision to not fix to the doc: https://www.notion.so/0xmacro/Mento-3-Fixes-afffa217cd824f5da6e4d7537fcb5e85?pvs=4#f0e60be945fd4d60a42b4c6e771d5408
