### ISSUE TITLE
MU06 Forum post

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/mento-core#384]
## Summary

We need a forum post describing the upcoming changes native USDC Pairs
similar to https://forum.celo.org/t/proposal-mento-upgrade-mu04-phase-out-v1-fully-transition-to-v2-and-update-stabletoken/7034

## Acceptance Criteria 
- [ ] forum post is written and posted

**Comment by philbow61** [comment]
forum post in notion here 
https://www.notion.so/mentolabs/MU05-Forum-post-5d06df51bb8344468fb0a3e7c62aa3ea?pvs=4

**Comment by nvtaveras** [comment]
Forum post pubished on Friday https://forum.celo.org/t/proposal-mento-upgrade-mu05-native-usdc-integration/7545
