### ISSUE TITLE
Create production fractal app

### ISSUE THREAD

**Issue by baroooo** [mento-protocol/mento-core#399]
### Description

We need to create a Fractal app in production environment. It will be similar to the staging env in terms of configuration but we need to remind Fractal to add an exception for Crimea, Donetsk and Luhansk when the integration is ready.

### Acceptance Criteria
- [x] Created the fractal app in production env
- [x] Updated vercel env vars to use the new production app
- [ ] Pinged Fractal to add exception for Crimea, Donetsk and Luhansk regions
- [x] Callback URLs defined and configured correctly.
- [x] Block lists based on residency and nationality are defined.
- [x] Fractal ID's app name should be "MENTO Airdrop"

**Comment by denviljclarke** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/vQsgD075RK/estimate/4) in Grooming - Apr 4

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by bayological** [comment]
@baroooo I think we need to update the URLs to be airdrop instead of airgrab, but we should confirm with @olenovyk

**Comment by nvtaveras** [comment]
LGTM 👍
