### ISSUE TITLE
Final Alfajores deployment

### ISSUE THREAD

**Issue by baroooo** [mento-protocol/mento-core#400]
### Description

After the recent changes, and fixes for the contest findings we need to fix the post deployment checks, and deploy the final version to the alfajores.
After the deployment, fork tests should be updated too

### Acceptance Criteria
- [ ] Final contracts are deployed to Alfajores
- [ ] Post deployment checks are green
- [ ] Automated integration tests are green 
- [ ] SDK uses the latest deployments

**Comment by denviljclarke** [comment]
**Story Points: 5**
  [See the discussion](https://action.parabol.co/meet/vQsgD075RK/estimate/2) in Grooming - Apr 4

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
