### ISSUE TITLE
Spike: Investigate Rari diff

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/mento-core#403]
**Description**
The code we used for the Rari locking component is different from the code Rari currently has deployed onchain.
This ticket is about investigating the difference and getting a better understanding of what they changed and how confident we feel about those changes.
The changes seem to be mostly in the broken line library. 
- Rari onchain contract: https://etherscan.io/address/0x51c37534ef4bb272cac10ab596ae843f786fd793#code
- The code we use: https://github.com/rarible/locking-contracts/tree/main/contracts
- https://github.com/rarible/locking-contracts/commit/ac465bd9faf2bd8c14f9239ed5bfe5c60f45dc6c#diff-492335c5e0d7b68c4db21fc44bf3e14eb9264efc532d960f1d50d58c8b9374db

**Acceptance Criteria**
- [x] Document and evaluate the difference

**Comment by nvtaveras** [comment]
Wrote some notes here https://www.notion.so/mentolabs/Rari-diff-8fd513c5f74d4ed28dfbf28e5040f46a

**Comment by chapati23** [comment]
Reviewed, thx for the investigation.

What's our action plan, though? I'm missing next steps, i.e. "Reach out to Rari. IF they don't answer then we can do option a) ABC or option b) XYZ etc

**Comment by baroooo** [comment]
Reviewed the doc 👍 
Since the only meaningful difference is how we get the past value of a brokenline, I would say lets do our best to get answers from them and add more focused tests on unmatching code.

**Comment by nvtaveras** [comment]
As discussed during the last retro, going back to an old version at this point wouldn't be ideal since the audits ran on the latest version. So given the diff, the current action is to reach out to Rari and see if we can get any input from them on why the latest contracts were never deployed, and from there reassess.

**Comment by nvtaveras** [comment]
Wrote an update at the top of the notion page. TL;DR: Spoke to someone from Rari and they said that the main reason they haven't migrated it's because complexity of the migration and that not being their priority at the moment.
