### ISSUE TITLE
Integration test and experimentation for stable-to-stable swaps

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#416]
**Description**

Transition to a stable-to-stable swap mechanism for _small cap_ stables is described here: https://www.notion.so/mentolabs/Stable-to-stable-swaps-6c5ea72c3a324579a6c664ac9080cd54

Initial testing was done in the `test/stable-to-stable` branch.

Theoretically, the Broker is equipped to handle stable-to-stable pairs, but we haven't used it in practice, and we need to think of edge cases and make sure we add the necessary tests for this use case.

**Acceptance criteria**

- [ ] Integration tests are added covering the stable-to-stable usecase.

**Comment by philbow61** [comment]
existing integration tests cover the stable to stable swap. Once the Governance script is ready we can do proper onchain verification
