### ISSUE TITLE
Revert stable bucket cap size changes

### ISSUE THREAD

**Issue by ole-nov** [mento-protocol/mento-core#43]
**Description**
An [issue](https://github.com/celo-org/celo-monorepo/issues/5849) was created some time ago to add a cap to the stable bucket size, but never made its way to Mainnet. In order to maintain consistency this change should be reverted in the Celo mono repo and Mento core repos. The issue the change was supposed to be address will be handled by the new trading limits that will be brought in with McMint.

**Acceptance Criteria**

- [x] Revert the changes from the PR https://github.com/celo-org/celo-monorepo/pull/9318 in the celo-monorepo
- [x] Revert the changes for the same PR in mento-core (as a hotfix).
- [x] Remove references to code in tests
- [x] Remove references(if any) to code in contractKit

**Comment by ninocomputer** [comment]
pr in celo-monorepo: https://github.com/celo-org/celo-monorepo/pull/9979

**Comment by ninocomputer** [comment]
pr in mento-core: https://github.com/mento-protocol/mento-core/pull/45
