### ISSUE TITLE
Collect list of 1st and 3rd party cookie providers for mentolabs.xyz

### ISSUE THREAD

**Issue by chapati23** [mento-protocol/mento-core#436]
- [ ] Fill out sections highlighted in yellow in this [cookie policy template](https://docs.google.com/document/d/1HqCzEdjFIZo9U3iZ4DOaN0cav0V0J7zL/)
- [ ] Send completed doc to Sandra
- [ ] Get Sandra's approval

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sprint-6458911097b7ec002c15f0d6/issues/mento-protocol/mento-core/436?planning-poker) with Zenhub @chapati23 @denviljclarke @nvtaveras @philbow61 @RyRy79261
