### ISSUE TITLE
Governance website throws error

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-core#453]
Example from Victoria:

![Image](https://github.com/mento-protocol/mento-core/assets/6872903/6e63a9a1-edc9-4550-81dd-f924d662753c)

Related to code that forces user to be on CELO

Partial replication:
- Switch wallet to non celo chain
- Run app locally

**Comment by RyRy79261** [comment]
Rainbow wallet is not sufficiently developed to allow for expected wallet behaviour
https://github.com/rainbow-me/browser-extension/issues/1361#issuecomment-1963320955
