### ISSUE TITLE
Implement Google Cloud Function that triggers the relayer contracts

### ISSUE THREAD

**Issue by chapati23** [mento-protocol/mento-core#460]
### Requirements
- [ ] Implement trigger cloud function [according to spec](https://www.notion.so/mentolabs/v1-5-Chainlink-Relayer-Tech-Spec-230fd1ff82b14102a74c7edc5791f566?pvs=4#7b7bc94e6bd64f1d8edbba5409f57e35)

This should include setting up of the private keys in the secret manager and making them accessible to the function.

### What's done already
- [x] There is a deployed cloud function [defined here](https://github.com/mento-protocol/oracle-relayer/blob/main/infra/cloud_function.tf)
- [x] Typescript + nodemon setup, all pretty much ready for completing the implementation

### What's still missing
- [x] Set up a private key for the function
- [x] Store it in a safe place via terraform ideally (i.e. secret manager?)
- [x] Give cloud function permissions to access the private key at runtime
- [x] Integrate viem
- [x] Integrate relayer contract ABI
- [x] Write transaction simulation code, we only want to send a real TX if the simulation works, make sure simulation errors are logged well so we can learn from them
- [x] Write transaction execution code (i.e. call the actual relay function on the relayer contract)
- [x] Write solid transaction monitoring and error-handling code (i.e. gracefully handle failed TXs, or TXs that take a long time considering cloud functions typically time out after 1 minute)

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/mento-core/460?planning-poker) with Zenhub @baroooo @chapati23 @denviljclarke
