### ISSUE TITLE
Set up on-chain monitoring for Chainlink Relayer

### ISSUE THREAD

**Issue by chapati23** [mento-protocol/mento-core#462]
### Requirements
- [x] Set up on-chain monitoring [according to spec](https://www.notion.so/mentolabs/v1-5-Chainlink-Relayer-Tech-Spec-230fd1ff82b14102a74c7edc5791f566?pvs=4#04d0092295874ea4884874970fe7a508)
- [x] Setup Discord Channel (1 for staging, 1 for prod)

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/mento-core/462?planning-poker) with Zenhub @baroooo @chapati23 @denviljclarke

**Comment by denviljclarke** [comment]
Need to sync w/ P2 & Nelson on this.
