### ISSUE TITLE
Write Runbook documenting how to deploy a new rate feed via the Chainlink Relayer system

### ISSUE THREAD

**Issue by chapati23** [mento-protocol/mento-core#466]
### Requirements
- [ ] Write a new runbook showing how to add new rate feeds based on the [process outlined in the spec](https://www.notion.so/mentolabs/v1-5-Chainlink-Relayer-Tech-Spec-230fd1ff82b14102a74c7edc5791f566?pvs=4#6a4144ff43824c7ea3cd3ab1de16e0f7)

### Update
I decided to just extend the spec description, felt like full separate runbook wasn't necessary as the process is pretty straightforward now: https://www.notion.so/mentolabs/Chainlink-Relayer-Spec-Oracles-v1-5-230fd1ff82b14102a74c7edc5791f566?pvs=4#6a4144ff43824c7ea3cd3ab1de16e0f7

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/mento-core/466?planning-poker) with Zenhub @baroooo @chapati23 @denviljclarke

**Comment by denviljclarke** [comment]
Spoke to @chapati23 & we decided to add an entry to the runbook table which syncs with the instructions in the Spec.

**Comment by denviljclarke** [comment]
Spoke to @chapati23 & we decided to add an entry to the runbook table which syncs with the instructions in the Spec.
