### ISSUE TITLE
Write Runbook documenting how to update an existing rate feed via the Chainlink Relayer system

### ISSUE THREAD

**Issue by chapati23** [mento-protocol/mento-core#467]
### Requirements
- [ ] Write a runbook outlining how to update rate feeds based on the [process outlined in the spec](https://www.notion.so/mentolabs/v1-5-Chainlink-Relayer-Tech-Spec-230fd1ff82b14102a74c7edc5791f566?pvs=4#9da0a82ac41c4ad5ae38f85fc0a9c95b)

### Update Aug 24th
I decided to just extend the spec description, felt like full separate runbook wasn't necessary as the process is pretty straightforward now: https://www.notion.so/mentolabs/Chainlink-Relayer-Spec-Oracles-v1-5-230fd1ff82b14102a74c7edc5791f566?pvs=4#9da0a82ac41c4ad5ae38f85fc0a9c95b

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/mento-core/467?planning-poker) with Zenhub @baroooo @chapati23 @denviljclarke
