### ISSUE TITLE
Deploy governance to Baklava

### ISSUE THREAD

**Issue by baroooo** [mento-protocol/mento-core#470]
Governance and token contracts are not deployed to baklava because of the low block limit. Since we have a mento protocol deployed on baklava and we still perform testnet deployments, we should deploy the mento governance to baklava and later transfer the ownership of the protocol to mento governance.

This would require a different deployment script that deploys contracts individually instead of a governance factory that deploys the contracts. Governance factory can be used as a reference for the deployment script.

Airgrab and Emission contracts and post deployment checks can be skipped.

### Requirements
- [ ] Deployment script for baklava deployment
- [ ] Mento token
- [ ] Locking Contracts
- [ ] Governance contracts

**Comment by chapati23** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Sprint-6458911097b7ec002c15f0d6/issues/mento-protocol/mento-core/470?planning-poker) with Zenhub @baroooo @bowd @philbow61
