### ISSUE TITLE
Submit a test governance proposal on mainnet

### ISSUE THREAD

**Issue by chapati23** [mento-protocol/mento-core#483]
We want to submit a real governance proposal on mainnet with some real execution code to see that our governance works end-to-end in production

### To Do
- [x] Write forum post draft
- [x] Get forum post reviewed
- [x] Publish forum post on forum.mento.org
- [x] Prepare execution data for a test proposal on mainnet (targets, calldatas, values)
- [ ] Submit proposal via Governance UI from Mento Labs multisig
- [ ] Check that both the watchdogs TG channel as well as the #governance-notifications discord channel receive an event upon proposal submission

**Comment by bayological** [comment]
How can we use this to also test MU0Next?

**Comment by chapati23** [comment]
Quickalerts went down literally 1 minute before the ProposalCreated event so we couldn't test the watchdog 😞

Next time
