### ISSUE TITLE
[SPIKE] Investigate which changes we need to do for the Celo L2 transition

### ISSUE THREAD

**Issue by baroooo** [mento-protocol/mento-core#520]

**Comment by RyRy79261** [comment]
3 months from now, block times should decrease to 1 second. this affects the locks potentially

**Comment by baroooo** [comment]
Created tickets from this spike:
https://app.zenhub.com/workspaces/sprint-6458911097b7ec002c15f0d6/issues/gh/mento-protocol/mento-core/538
https://app.zenhub.com/workspaces/sprint-6458911097b7ec002c15f0d6/issues/gh/mento-protocol/mento-deployment/236
https://app.zenhub.com/workspaces/sprint-6458911097b7ec002c15f0d6/issues/gh/mento-protocol/governance-tests/30
https://app.zenhub.com/workspaces/sprint-6458911097b7ec002c15f0d6/issues/gh/mento-protocol/mento-deployment/237
https://app.zenhub.com/workspaces/sprint-6458911097b7ec002c15f0d6/issues/gh/mento-protocol/mento-deployment/238
https://app.zenhub.com/workspaces/sprint-6458911097b7ec002c15f0d6/issues/gh/mento-protocol/mento-general/579
