### ISSUE TITLE
Write a forum post about upcoming changes

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#54]
> Blocked by https://github.com/mento-protocol/docs/issues/15

### Description

We need a forum post describing the upcoming changes to the Mento stack: multi-collateral mint and circuit breaker.

### Acceptance criteria

- Forum post is posted.

**Comment by ole-nov** [comment]
Draft (WIP): https://www.notion.so/Forum-post-upcoming-Mento-update-bc9fef9bb0c14d329f9bfcfcd79fa28f
