### ISSUE TITLE
Determine the initial pairs that will be deployed with McMint

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-core#55]
**Description**

**Acceptance Criteria**

- [ ] Update [migration plan](https://docs.google.com/document/d/1a_7DrxDKZmB5OS4SdvvLSwuT97omRVxa/edit?usp=sharing&ouid=115461431738185451043&rtpof=true&sd=true)

**Comment by bowd** [comment]
- cUSD/CELO
- cEUR/CELO
- cREAL/CELO
- cUSD/USDCet
