### ISSUE TITLE
Allow stable burning via Broker

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-core#58]
### Description

We're burning cStables via the burning-bot, which takes a long time and has an impact on Mento pools. The collateral we receive from the trading sessions goes back into the reserve. Ideally, we would have a way of directly burning stables instead.

For this, we can add a function `burnStableTokens(address token, uint256 amount)` to the Broker.

### Acceptance criteria 

- Add the permissionless `burnStableTokens(address token, uint256 amount)` function to the Broker
- Write tests for the functionality

**Comment by ninocomputer** [comment]
https://github.com/mento-protocol/mento-core/pull/74
