### ISSUE TITLE
Make the PricingModules un-upgradable and stateless

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#60]
### Description

The ConstantSumPricingModule and CrossProductPricingModules are currently stateful and include logic to be deployed as upgradable contracts. This shouldn't be the case. We will never want to upgrade them but can use them as plug-and-play targets for configuring pairs.

### Acceptance criteria

- [x] Any contracts which implement IPricingModule shouldn't be Ownable / Initializable
- [x] The contracts don't have a constructor or any storage variables

**Comment by philbow61** [comment]
#63
