### ISSUE TITLE
Determine oracle implicit rate paths for all pairs

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#73]
### Description

We will expose pairs for:
- cUSD / USDCet
- cEUR / USDCet
- cREAL / USDCet

We need to extend our oracles to provide oracle rates for these pairs, and thus we need implicit pair paths to configure our oracles.

### Acceptance criteria

- Implicit pair paths for each of the pairs above

**Comment by bayological** [comment]
For cUSD / USDCet we will be using the USDC / USD rate but what rates will we use for the other two? @sissnad

**Comment by sissnad** [comment]
> For cUSD / USDCet we will be using the USDC / USD rate but what rates will we use for the other two? @sissnad

My understanding regarding the phases was ther following:
1. We will start with cUSD/USDCet; no cEUR/USDCet and cREAL/USDCet
2. We will provide cStable swaps using FX rates which allow for implicit cEUR/USDCet and cREAL/USDCet swaps

Optional if implicit cEUR/USDCet and cREAL/USDCet swaps are to frictional

(3.  We will provide cEUR/USDCet and cREAL/USDCet providing additional implicit oracle rates  EUR/USDC and BRL/USDC)

**Comment by nvtaveras** [comment]
Cool that SGTM, it's just that last time I only brought up cUSD/USDCet on discord and didn't know where we landed on the other ones
