### ISSUE TITLE
Make Breakers configurable for specific rate feeds

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#81]
### Description

Currently, the BreakerBox has an array of registered breakers. When a new price is reported, the breaker iterates through the list and checks each breaker for the `rateFeedID`. This means that there is no way to configure a breaker that's only checked for one `rateFeed`. At the same time, the existing MedianDeltaBreaker has a global `priceChangeThreshold` which is checked for all rates. 

In order to increase how configurable the system is we need to tackle two things:
1. In the `BreakerBox` we need to have a way of specifying if a breaker is enabled for a given `rateFeedID` by storing a `mapping(address => mapping(address => bool)) breakerEnabled` that we can check with `breakerEnabled[breaker][rateFeedID]`. We will then check this mapping when deciding if a breaker should be verified.

2. In the `MedianDeltaBreaker` we want to have a global `uint256 defaultPriceChangeThreshold` and a configurable `mapping(address => uint256) priceChangeThreshold` where we can store the threshold by `rateFeedID`. Then when verifying the median, we use the default or the specific value for the rate feed if it's configured.

Notes:
- We have to treat the edge case when we're disabling a breaker for a rate feed if that breaker is already tripped. We should reset the trading mode of the rate feed to the default.

Side quests:
- Maybe rename `priceChange` to `rateChange` in the `MedianDeltaBreaker` to keep things consistent.
- **If the deployment branch gets merged while this is in-flight** the upgrade scripts need to be updated to reflect the change.

### Acceptance criteria

- [x] BreakerBox has a configurable mapping between breakers and rate feeds that it takes into account
- [x] MedianDeltaBreaker has configurable thresholds per rate feed
- [x] We have tests that reflect general code paths, including but not limited to when a breaker which was tripped is disabled from a price feed.

**Comment by ninocomputer** [comment]
[pr](https://github.com/mento-protocol/mento-core/pull/83)
