### ISSUE TITLE
Make new Baklava deployment

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-core#98]
**Description**

We have an existing Baklava deployment with slightly older versions of the contracts (before the audit code freeze).
We want to:
- Rollback what's necessary in terms of Governance Proposal changes. eg:
  - remove existing Broker from Reserve.sol as exchangeSpender
  - maybe others?
- Execute a new deployment on baklava

**Acceptance criteria**

- [ ] MU01 is deployed to Baklava
- [ ] Add a page on creating a pool in Docs
- [ ] Add addresses to the Contracts section in Docs
- [x] Simulation with test swap to confirm MU01 works as intended
- [ ] [Deployment guide](https://www.notion.so/Core-Contracts-Deployment-Guide-3f68a4075e7f4a429f304ba8225d3c44) Is updated to reflect changes
- [x] Upgrades/deploy folder follows new script convention with the following standard scripts:
       - MUXX-00-New-Proxies.sol
       - MUXX-01-New-Proxy-Implementations.sol
       - MUXX-02-Upgraded-Proxy-Implementations.sol
       - MUXX-03-Nonupgradable-Contracts.sol
       - MUXX-04-Misc.sol
       - MUXX-05-Governance-Ownership-Transfer.sol

**Comment by ninocomputer** [comment]
👀

**Comment by bayological** [comment]
👀
